// <auto-generated />
using System;
using MAS_BE.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAS_BE.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230829182447_xcv")]
    partial class xcv
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MAS_BE.Entities.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Discount")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Discount = true,
                            Email = "email@gmail.com",
                            FirstName = "Gleb",
                            LastName = "Ivanov",
                            TelNumber = "12312341"
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.Ingridient", b =>
                {
                    b.Property<int>("IdIngridient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("IdIngridient");

                    b.ToTable("Ingridients");

                    b.HasData(
                        new
                        {
                            IdIngridient = 1,
                            Title = "First Ingridient",
                            Weight = 23.5f
                        },
                        new
                        {
                            IdIngridient = 2,
                            Title = "Second Ingridient",
                            Weight = 25.5f
                        },
                        new
                        {
                            IdIngridient = 3,
                            Title = "Third Ingridient",
                            Weight = 21.5f
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.Manager", b =>
                {
                    b.Property<int>("IdManager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("IdManager");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("MAS_BE.Entities.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdManager")
                        .HasColumnType("int");

                    b.Property<int>("IdOrderType")
                        .HasColumnType("int");

                    b.Property<int?>("IdReceipt")
                        .HasColumnType("int");

                    b.Property<int?>("IdWaiter")
                        .HasColumnType("int");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdManager");

                    b.HasIndex("IdOrderType");

                    b.HasIndex("IdReceipt")
                        .IsUnique()
                        .HasFilter("[IdReceipt] IS NOT NULL");

                    b.HasIndex("IdWaiter");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            IdOrder = 1,
                            ClosedAt = new DateTime(2023, 8, 29, 20, 24, 47, 573, DateTimeKind.Local).AddTicks(387),
                            CreateAt = new DateTime(2023, 8, 29, 20, 24, 47, 573, DateTimeKind.Local).AddTicks(41),
                            IdClient = 1,
                            IdOrderType = 1,
                            IdReceipt = 1,
                            Sum = 30.4f
                        },
                        new
                        {
                            IdOrder = 2,
                            CreateAt = new DateTime(2023, 8, 29, 20, 24, 47, 573, DateTimeKind.Local).AddTicks(1202),
                            IdClient = 1,
                            IdOrderType = 1,
                            Sum = 13f
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.OrderProduct", b =>
                {
                    b.Property<int>("IdOrderProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.HasKey("IdOrderProduct");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdProduct");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            IdOrderProduct = 1,
                            IdOrder = 1,
                            IdProduct = 1
                        },
                        new
                        {
                            IdOrderProduct = 2,
                            IdOrder = 1,
                            IdProduct = 2
                        },
                        new
                        {
                            IdOrderProduct = 3,
                            IdOrder = 1,
                            IdProduct = 3
                        },
                        new
                        {
                            IdOrderProduct = 4,
                            IdOrder = 1,
                            IdProduct = 5
                        },
                        new
                        {
                            IdOrderProduct = 5,
                            IdOrder = 2,
                            IdProduct = 4
                        },
                        new
                        {
                            IdOrderProduct = 6,
                            IdOrder = 2,
                            IdProduct = 6
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.OrderType", b =>
                {
                    b.Property<int>("IdOrderType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrderType");

                    b.ToTable("OrderTypes");

                    b.HasData(
                        new
                        {
                            IdOrderType = 1,
                            Title = "Take away"
                        },
                        new
                        {
                            IdOrderType = 2,
                            Title = "For here"
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdProductCategory")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdProductCategory");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            IdProduct = 1,
                            IdProductCategory = 1,
                            Price = 3.7f,
                            Title = "Pizza"
                        },
                        new
                        {
                            IdProduct = 2,
                            IdProductCategory = 1,
                            Price = 11f,
                            Title = "Burger"
                        },
                        new
                        {
                            IdProduct = 3,
                            IdProductCategory = 1,
                            Price = 9.5f,
                            Title = "Sushi"
                        },
                        new
                        {
                            IdProduct = 4,
                            IdProductCategory = 2,
                            Price = 4.8f,
                            Title = "Cosmopolitan"
                        },
                        new
                        {
                            IdProduct = 5,
                            IdProductCategory = 2,
                            Price = 6.2f,
                            Title = "Old Fashion"
                        },
                        new
                        {
                            IdProduct = 6,
                            IdProductCategory = 2,
                            Price = 8.2f,
                            Title = "Pornstar Martini"
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.ProductCategory", b =>
                {
                    b.Property<int>("IdProductCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProductCategory");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            IdProductCategory = 1,
                            Title = "Food"
                        },
                        new
                        {
                            IdProductCategory = 2,
                            Title = "Drink"
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.ProductIngridient", b =>
                {
                    b.Property<int>("IdProductIngridient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdIngridient")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.HasKey("IdProductIngridient");

                    b.HasIndex("IdIngridient");

                    b.HasIndex("IdProduct");

                    b.ToTable("ProductIngridients");

                    b.HasData(
                        new
                        {
                            IdProductIngridient = 1,
                            IdIngridient = 1,
                            IdProduct = 1
                        },
                        new
                        {
                            IdProductIngridient = 2,
                            IdIngridient = 3,
                            IdProduct = 1
                        },
                        new
                        {
                            IdProductIngridient = 3,
                            IdIngridient = 2,
                            IdProduct = 2
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.Receipt", b =>
                {
                    b.Property<int>("IdReceipt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdReceipt");

                    b.ToTable("Receipts");

                    b.HasData(
                        new
                        {
                            IdReceipt = 1,
                            PaymentMethod = 0,
                            Sum = 30.4f,
                            createdAt = new DateTime(2023, 8, 29, 20, 24, 47, 572, DateTimeKind.Local).AddTicks(4140)
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.Report", b =>
                {
                    b.Property<int>("IdReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdManger")
                        .HasColumnType("int");

                    b.Property<int>("OrderQuantity")
                        .HasColumnType("int");

                    b.Property<float>("Revenue")
                        .HasColumnType("real");

                    b.HasKey("IdReport");

                    b.HasIndex("IdManger");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            IdReport = 1,
                            CreateAt = new DateTime(2023, 8, 29, 20, 24, 47, 566, DateTimeKind.Local).AddTicks(9082),
                            OrderQuantity = 3,
                            Revenue = 100f
                        });
                });

            modelBuilder.Entity("MAS_BE.Entities.Waiter", b =>
                {
                    b.Property<int>("IdWaiter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Student")
                        .HasColumnType("bit");

                    b.Property<string>("TelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdWaiter");

                    b.ToTable("Waiters");
                });

            modelBuilder.Entity("MAS_BE.Entities.Order", b =>
                {
                    b.HasOne("MAS_BE.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("IdClient");

                    b.HasOne("MAS_BE.Entities.Manager", "Manager")
                        .WithMany("Orders")
                        .HasForeignKey("IdManager");

                    b.HasOne("MAS_BE.Entities.OrderType", "OrderType")
                        .WithMany("Orders")
                        .HasForeignKey("IdOrderType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAS_BE.Entities.Receipt", "Receipt")
                        .WithOne("Order")
                        .HasForeignKey("MAS_BE.Entities.Order", "IdReceipt");

                    b.HasOne("MAS_BE.Entities.Waiter", "Waiter")
                        .WithMany()
                        .HasForeignKey("IdWaiter");

                    b.Navigation("Client");

                    b.Navigation("Manager");

                    b.Navigation("OrderType");

                    b.Navigation("Receipt");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("MAS_BE.Entities.OrderProduct", b =>
                {
                    b.HasOne("MAS_BE.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAS_BE.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MAS_BE.Entities.Product", b =>
                {
                    b.HasOne("MAS_BE.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("IdProductCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("MAS_BE.Entities.ProductIngridient", b =>
                {
                    b.HasOne("MAS_BE.Entities.Ingridient", "Ingridient")
                        .WithMany("ProductIngridients")
                        .HasForeignKey("IdIngridient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAS_BE.Entities.Product", "Product")
                        .WithMany("ProductIngridients")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingridient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MAS_BE.Entities.Report", b =>
                {
                    b.HasOne("MAS_BE.Entities.Manager", "Manager")
                        .WithMany("Reports")
                        .HasForeignKey("IdManger");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MAS_BE.Entities.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MAS_BE.Entities.Ingridient", b =>
                {
                    b.Navigation("ProductIngridients");
                });

            modelBuilder.Entity("MAS_BE.Entities.Manager", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MAS_BE.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("MAS_BE.Entities.OrderType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MAS_BE.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("ProductIngridients");
                });

            modelBuilder.Entity("MAS_BE.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MAS_BE.Entities.Receipt", b =>
                {
                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
